### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'app'

### ISSUE THREAD

**Issue by Chertoganov** [marinkaz/decagon#13]
AttributeError: module 'tensorflow' has no attribute 'app'

(base) C:\Users\chert\decagon>python main.py
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from decagon.deep.optimizer import DecagonOptimizer
  File "C:\Users\chert\decagon\decagon\deep\optimizer.py", line 4, in <module>
    flags = tf.app.flags
AttributeError: module 'tensorflow' has no attribute 'app'

(base) C:\Users\chert\decagon>

how to solve this error ??

**Comment by Tschichen** [comment]
Got the same error. Could you fix it?

**Comment by Chertoganov** [comment]
nope....
)

**Comment by hahahhehe** [comment]
You need to use the vision of tensorflow is 1.8.0.

**Comment by junfu96** [comment]
ERROR: Could not find a version that satisfies the requirement tensorflow==1.8.0 (from versions: 1.13.1, 1.13.2, 1.14.0, 1.15.0, 1.15.2, 1.15.3, 1.15................
